/**
 * Created by user on 07.09.2015.
 */

data['PROD_CASH_CRED'] = 'N';
data['RES_CALL_TOTAL'] = 'C_NULL';
data['RES_CALL_HOME_PHONE'] = 'Y';
data['RES_CALL_WORK_PHONE'] = 'Y';
data['RES_CALL_MOB_PHONE'] = 'N';
data['APP_EMPL_SOCIALSTATUS'] = 'PENS';
data['RES_CALL_LAST_HOME'] = 'C_NULL';
data['RES_CALL_LAST_WORK'] = 'C_NULL';
data['RES_CALL_LAST_MOB'] = 'C_NULL';
data['PROD_PACK_TYPE'] = 'UNI';
data['PROD_CHAR_TYPE'] = 'UNIPACKSAS';
data['PROD_CHAR_REFERENCE']= 'SAPBjhgfsjdgfjku';
data['APP_EMPL_RANK'] = 'WORKER';
data['APP_EMPL_TIMEEMPL'] = 21;
data['APP_EMPL_ORGTYPE'] = 'IT';
data['PROD_CHAR_BANK'] = 'PB';
data['PROD_PACK_TYPE'] = 'UNI';
data['APP_CUST_IMPORTANT_PRODUCT'] = '';
data['RES_LIMIT_ITOG_TYPE'] = 'VNESH';
//data['RES_CALL_TOTAL_HIST'] = '';
data['PROD_CHAR_BRANCH'] = 'DNH0';
data['RES_CALL_DIALOGE_TYPE'] = 'NORMAL';
data['RES_DEC_AUTO'] = 'Y';
data['RES_HIST_RESTRICTION'] = '';
data['DATA_WORK_TOP1000'] = 'N';
data['PROD_CHAR_LIMITREQUESTED'] = 5000;
//data['RES_CALL_LIMIT'] = 5000;
//data['RES_LIMIT_CALL'] = 5000;
//data['DATA_CARD_UPGRADE_LIMIT'] = ;
data['RES_CUST_ISID'] = 'Y';
data['RES_CUST_ISID_FRAUD'] = 'N';
//APP_CUST_SPECIALPROJECT
data['LOCAL_TICKET_FLAG_TEHPASSP'] = 'N';
data['LOCAL_TICKET_FLAG_FORPASSP'] = 'N';
data['RES_CRED_LIM'] = 0;
data['RES_TO_KC'] = 'N';
//LOCAL_CALL_COMMENT
data['FRAUD_FRAUD_SUSPICTION'] = 'N';
data['APP_SOCSTATUS_RESIDENT'] = 'Y';
data['RES_LIMIT_P48'] = 300;
data['RES_LIMIT_ITOG'] = 4500;
//RES_DEC_TEXT
data['RES_TYPE_SMS'] = 'Y';
data['RES_COMMENT_NO_AUTO'] = '';
data['RES_HISTORY_REAS_CODE'] = 'A101;A111';
data['PRE_REAS_CODE_TABLE'] = new Array();
data['PRE_REAS_CODE_TABLE'].push('A101');
data['PRE_REAS_CODE_TABLE'].push('A111');
data['APP_PHONE_TYPE_CALL'] = new Array();
data['APP_PHONE_TYPE_CALL'].push('WORK');
data['APP_PHONE_TYPE_CALL'].push('HOME');
data['APP_PHONE_TYPE_CALL'].push('MOB');
//DATA_CRED_REFERENCE
data['LOCAL_BLCL_CONTROL'] = new Array();
data['LOCAL_BLCL_CONTROL'].push('');


data['param'] = new Array('RES_DEC_REAS_CODE_TABLE','PROD_CASH_CRED','RES_CALL_HOME_PHONE','RES_CALL_WORK_PHONE','RES_CALL_MOB_PHONE','APP_EMPL_SOCIALSTATUS','PROD_PACK_TYPE',
    'PROD_CHAR_TYPE','PROD_CHAR_REFERENCE','APP_EMPL_RANK','APP_EMPL_TIMEEMPL','APP_EMPL_ORGTYPE','PROD_CHAR_BANK','PROD_PACK_TYPE','APP_CUST_IMPORTANT_PRODUCT','RES_LIMIT_ITOG_TYPE','RES_CALL_TOTAL_HIST',
    'PROD_CHAR_BRANCH','RES_CALL_DIALOGE_TYPE','RES_DEC_AUTO','RES_HIST_RESTRICTION','DATA_WORK_TOP1000','PROD_CHAR_LIMITREQUESTED','RES_LIMIT_CALL','DATA_CARD_UPGRADE_LIMIT','RES_CUST_ISID',
    'RES_CUST_ISID_FRAUD','APP_CUST_SPECIALPROJECT','LOCAL_TICKET_FLAG_TEHPASSP','LOCAL_TICKET_FLAG_FORPASSP','RES_CRED_LIM','RES_TO_KC','FRAUD_FRAUD_SUSPICTION','APP_SOCSTATUS_RESIDENT',
    'RES_LIMIT_P48','RES_LIMIT_ITOG','RES_DEC_TEXT','RES_TYPE_SMS','RES_COMMENT_NO_AUTO','RES_HISTORY_REAS_CODE','APP_PHONE_TYPE_CALL','LOCAL_BLCL_CONTROL','RES_DEC_REAS_FINAL_CODE','RES_PROD_TYPE','APP_CUST_ID',	'RES_RIP_APPLICATION');

/*'UNEMP_LIM','MINIM_LIM','MAXIM_LIM','RESTR_LIM','TIMEEMPL_LIM',*/

/*[PROD_CASH_CRED,RES_CALL_TOTAL,RES_CALL_HOME_PHONE,RES_CALL_WORK_PHONE,RES_CALL_MOB_PHONE,APP_EMPL_SOCIALSTATUS,RES_CALL_LAST_HOME,RES_CALL_LAST_WORK,RES_CALL_LAST_MOB,PROD_PACK_TYPE,
 PROD_CHAR_TYPE,PROD_CHAR_REFERENCE,APP_EMPL_RANK,APP_EMPL_TIMEEMPL,APP_EMPL_ORGTYPE,PROD_CHAR_BANK,PROD_PACK_TYPE,APP_CUST_IMPORTANT_PRODUCT,RES_LIMIT_ITOG_TYPE,RES_CALL_TOTAL_HIST,
 PROD_CHAR_BRANCH,RES_CALL_DIALOGE_TYPE,RES_DEC_AUTO,RES_HIST_RESTRICTION,DATA_WORK_TOP1000,PROD_CHAR_LIMITREQUESTED,RES_CALL_LIMIT,RES_LIMIT_CALL,DATA_CARD_UPGRADE_LIMIT,RES_CUST_ISID,
 RES_CUST_ISID_FRAUD,APP_CUST_SPECIALPROJECT,LOCAL_TICKET_FLAG_TEHPASSP,LOCAL_TICKET_FLAG_FORPASSP,RES_CRED_LIM,RES_TO_KC,LOCAL_CALL_COMMENT,FRAUD_FRAUD_SUSPICTION,APP_SOCSTATUS_RESIDENT,
 RES_LIMIT_P48,RES_LIMIT_ITOG,RES_DEC_TEXT,RES_TYPE_SMS,RES_COMMENT_NO_AUTO,RES_HISTORY_REAS_CODE,APP_PHONE_TYPE_CALL,LOCAL_BLCL_CONTROL,DATA_CRED_REFERENCE,RES_DEC_REAS_FINAL_CODE]*/

/* {
 "APPLIC_ID": "150330TSTT054989PKEG",
 "RTDM_ID": 367351
 }
 501775
 150427B1TT494914PYHH

 */