/*
-RES_CALL_MOB_TOTAL	RES_CALL_MOB_TOTAL
-RES_CALL_WORK_TOTAL	RES_CALL_WORK_TOTAL
-RES_CALL_WORK_BAL	RES_CALL_WORK_BAL
-LOCAL_PHONE_WORK_ARRAY	LOCAL_PHONE_WORK_ARRAY
-RES_CALL_MOB_BAL	RES_CALL_MOB_BAL
-LOCAL_PHONE_MOB_ARRAY	LOCAL_PHONE_MOB_ARRAY
-RES_CALL_TOTAL	RES_CALL_TOTAL
-RES_CALL_BAL	RES_CALL_BAL
-FIN_RES_DEC_FINAL_FLOW	RES_DEC_FINAL_FLOW
-FIN_RES_LIMIT_CALL	RES_LIMIT_CALL
-RES_CALL_ISID_FRAUD	RES_CALL_ISID_FRAUD
-FIN_FRAUD_FRAUD_SUSPICTION	FRAUD_FRAUD_SUSPICTION
-LOCAL_CALL_COMMENT	LOCAL_CALL_COMMENT
-FIN_RES_DEC_REAS_FINAL_CODE	RES_DEC_REAS_FINAL_CODE
-FIN_RES_BI	RES_BI
-FIN_RES_DEC_FINAL_COMMENT	RES_DEC_FINAL_COMMENT
-FIN_RES_HISTORY_REAS_CODE	RES_HISTORY_REAS_CODE
-FIN_RES_LIMIT_P48	RES_LIMIT_P48
-FIN_REAS_CODE_TABLE	FIN_REAS_CODE_TABLE
-FIN_RES_LIMIT_ITOG	RES_LIMIT_ITOG
-FIN_RES_LIMIT_ITOG_TYPE	RES_LIMIT_ITOG_TYPE
-FIN_RES_HIST_RESTRICTION	RES_HIST_RESTRICTION
-FIN_RES_DEC_TEXT	RES_DEC_TEXT
-FIN_RES_TYPE_SMS	RES_TYPE_SMS
-FIN_RES_COMMENT_NO_AUTO	RES_COMMENT_NO_AUTO
-FIN_RES_DEC_CATEGORY	RES_DEC_CATEGORY
-FIN_RES_DEC_AUTO	RES_DEC_AUTO
-FIN_RES_CHAR_PLAT_MIN	RES_CHAR_PLAT_MIN
-FIN_RES_PROD_TYPE	RES_PROD_TYPE*/

data['param_save'] = {
    'RES_CALL_MOB_TOTAL': data['RES_CALL_MOB_TOTAL'],
    'RES_CALL_WORK_TOTAL':data['RES_CALL_WORK_TOTAL'],
    'RES_CALL_HOME_TOTAL':data['RES_CALL_HOME_TOTAL'],
    'RES_CALL_WORK_BAL': data['RES_CALL_WORK_BAL'],
    'RES_CALL_MOB_BAL': data['RES_CALL_MOB_BAL'],
    'RES_CALL_HOME_BAL': data['RES_CALL_HOME_BAL'],
    'LOCAL_PHONE_WORK_ARRAY':data['LOCAL_PHONE_WORK_ARRAY'],
    'LOCAL_PHONE_MOB_ARRAY':data['LOCAL_PHONE_MOB_ARRAY'],
    'LOCAL_PHONE_HOME_ARRAY':data['LOCAL_PHONE_HOME_ARRAY'],
    'RES_CALL_TOTAL':data['RES_CALL_TOTAL'],
    'RES_CALL_BAL':data['RES_CALL_BAL'],
    'FIN_RES_DEC_FINAL_FLOW':data['RES_DEC_FINAL_FLOW'],
    'FIN_RES_LIMIT_CALL':data['RES_LIMIT_CALL'],
    'RES_CALL_ISID_FRAUD':data['RES_CALL_ISID_FRAUD'],
    'FIN_FRAUD_FRAUD_SUSPICTION': data['FRAUD_FRAUD_SUSPICTION'],
    'LOCAL_CALL_COMMENT':data['LOCAL_CALL_COMMENT'],
    'FIN_RES_DEC_REAS_FINAL_CODE':data['RES_DEC_REAS_FINAL_CODE'],
    'FIN_RES_BI':data['RES_BI'],
    'FIN_RES_DEC_FINAL_COMMENT':data['RES_DEC_FINAL_COMMENT'],
    'FIN_RES_HISTORY_REAS_CODE':data['RES_HISTORY_REAS_CODE'],
    'FIN_RES_LIMIT_P48':data['RES_LIMIT_P48'],
    'FIN_REAS_CODE_TABLE':data['FIN_REAS_CODE_TABLE'],
    'FIN_RES_LIMIT_ITOG':data['RES_LIMIT_ITOG'],
    'FIN_RES_LIMIT_ITOG_TYPE':data['RES_LIMIT_ITOG_TYPE'],
    'FIN_RES_HIST_RESTRICTION':data['RES_HIST_RESTRICTION'],
    'FIN_RES_DEC_TEXT':data['RES_DEC_TEXT'],
    'FIN_RES_TYPE_SMS':data['RES_TYPE_SMS'],
    'FIN_RES_COMMENT_NO_AUTO':data['RES_COMMENT_NO_AUTO'],
    'FIN_RES_DEC_CATEGORY':data['RES_DEC_CATEGORY'],
    'FIN_RES_DEC_AUTO':data['RES_DEC_AUTO'],
    'FIN_RES_CHAR_PLAT_MIN':data['RES_CHAR_PLAT_MIN'],
    'FIN_RES_PROD_TYPE':data['RES_PROD_TYPE']

};
